FROM centos:7

COPY download-tomcat.sh download-tomcat.sh
RUN yum -y install wget && yum clean all && chmod a+x download-tomcat.sh && ./download-tomcat.sh

RUN yum install -y java-1.8.0-openjdk && yum clean all
ENV JAVA_HOME /etc/alternatives/jre

COPY server.xml /tomcat/apache-tomcat-9.0.16/conf/server.xml
COPY rover-image-publisher.war /tomcat/apache-tomcat-9.0.16/webapps/rover-image-publisher.war

WORKDIR tomcat/apache-tomcat-9.0.16/bin
CMD ./catalina.sh run

